### ISSUE TITLE
Polish translation - step 10 - mistranslated 

### ISSUE THREAD

**Issue by apopanda** [GliaX/tourniquet#19]
Title.
In the polish translation, it says:
Gdy drążek wyciągarki został umieszczony, załóż względem niego pewien luz paska.
which roughly translates to 
"When you insert the windlass, allow some slack in the belt". 
As per talk with mr M. Al-Attar on Mattermost, in this step we should remove the slack, not add more of it / allow some of it.

**Comment by tareko** [comment]
Thank you @apopanda . Could you give a new translation?

**Comment by tareko** [comment]
I see the error and how it was misinterpreted. "take up any slack" was interpreted as "add slack"

**Comment by apopanda** [comment]
Copypasting from mattermost:
The translation: 
Gdy drążek wyciągarki został nawleczony na wewnętrzny pasek, napnij pasek. Wewnętrzny pasek powinien być maksymalnie naprężony.

Translates to when the windlass is put through the inner belt, make it tight. The inner belt should be maximally tight


I also think we might want to consider removing idioms from the english version, like the one I mentioned earlier. Running them through google translate to make sure what they mean sometimes get conflicting results. Simple / idiot proof language would be better in this case I feel

**Comment by tareko** [comment]
That's a great suggestion, @apopanda . I will review for simple english
