### ISSUE TITLE
questions regarding webbing materials

### ISSUE THREAD

**Issue by DenysGonchar** [GliaX/tourniquet#20]
I'm looking for the recommended webbing materials at the Polish/European stores, and experience some difficulties. That would be nice to understand what are the possible alternatives.
Also some information is missing in [assembly_instructions](../blob/master/assembly_instructions/INSTRUCTIONS_EN.md)

please answer these questions:

- It's hard to find 3,85 cm wide webbing/velcro strap (3,85cm velcro is not available at all), and it's hard to work with 3,5 cm strap. So please clarify if any of the following alternatives is fine:
  - 4 cm is a very common and easy to find width. But taking into account that width was explicitly reduced in this [commit](https://github.com/GliaX/tourniquet/commit/dd9fa25da8adfd86979d8be48006c96247e79232), I assume that 4cm is not a recommended option for the current design of the plastic parts. But if 4cm is a bit too wide, can we just extend the holes a little in the plastic parts (and probably increase the size of parts as well) instead of narrowing the width of the belt?
  - 3,5 cm wide webbing is less common than 4cm, but it's possible to find. However, it's harder to sew the belt. Can we take a bit narrower internal belt in this case, e.g. 2cm wide instead of 2,5
- A polyester-cotton webbing strap for the back face of the belt is not common, usually it's either synthetic or cotton. From my understanding, pure cotton is a better option as there can be a direct contact with the skin. Also, it doesn't look like we put too much tension on the back face belt while tightening the tourniquet, so reinforcement with polyester is not necessary. Please clarify if 100% cotton strap is fine for the back face of the belt.
- There is no information about the required thickness of the back face of the belt. From my understanding, it must distribute the pressure generated by the internal belt. But from another point, if it's too thick, it can cause issues during application (e.g. it can be hard to fit in into the buckle). It seems that 2-2,5 mm is an optimal thickness, but it's just my impression and I don't have any real field experience. There are many options available in the market, from 1mm to 4mm thick, so please provide some recommendation.
- I cannot find nylon webbing strap for internal belt, more over there are no webbing straps made of nylon in the local market. But there are 2 other options that are widely available: polyester and polypropylene. Both materials are stretching less than nylon, which is better in our case. 
  - according to the various sources available for analysis, polyester shows even better abrasion and UV resistance than nylon
  - polypropylene is less strong/resistant, from another perspective it's also widely available, and it's also used in heavy-duty applications. I'm not sure how critical UV resistance is, since the strap is mostly covered from all sides. And also we are going to tight it just once or a maybe few times. So maybe it's a "good enough" option.

And in the end, it is very important to have some well-defined QA procedures. It's required for mass production, checking prototypes and testing if something is changing (e.g. usage of alternative materials, minor optimizations in sewing, etc.)

Please, provide your comments and extend assembly instructions. I can help with Ukrainian, Polish and Russian translations.

**Comment by apopanda** [comment]
Note: none of what I'm saying comes from @tareko or Glia, I'm just another maker that made some units already, around your area.

The 40mm velcro you mention will be 3.85 if you measure it. Most of the "40mm" velcro is actually 1.5 inch, which is 3.8. As for the webbing, you can find it for example here: https://allegro.pl/oferta/tasma-nosna-bawelniano-poliestrowa-38mm-1m-11809897469 - I see that you're based in Cracow, so I hope allegro links work for you. I wouldn't go to 3.5cm webbing and internal belt - the STLs are made for the "40mm" which is actually a 1.5 inch. 

As for the nylon - try 'poliamide' - more hits that way. No idea if there's much difference, for sure it's closer than polyester is.

As for the QA procedures - yeah, it's a problem Glia is trying to solve. They're working on getting the documentation to be more precise, and the testing is on the horizon, but it's still some time away. There are independent groups trying to figure it out in the meantime, nothing concrete yet though.

**Comment by jenwilsonglia** [comment]
Closing this issue as the outer strap info has been changed/specified on the updated BOM.
