### ISSUE TITLE
Review english documentation for Simple English

### ISSUE THREAD

**Issue by tareko** [GliaX/tourniquet#21]
Review English Language documentation to reduce chances of translation errors.

First raised by @apopanda in Issue #19

**Comment by apopanda** [comment]
I'll raise the step 10 issue too. Today at the meeting we opted for adding 2.5cm of slack to the windlass rod. This needs to be specified instead of the "remove all slack" we have there right now.

**Comment by jenwilsonglia** [comment]
Closing this issue due to updated comprehensive assembly instructions in simple English.
