### ISSUE TITLE
Please add some more instructions for assembly

### ISSUE THREAD

**Issue by sbamueller** [GliaX/tourniquet#3]
Hi,
I'm just trying ti print the tourniquet. What kind of velcro and nylon straps do I need?

**Comment by tareko** [comment]
Hi @sbamueller ! Thank you for this. Indeed one of the deficiencies at the moment is a lack of information on the non-printed parts.

@shakersh : Could you comment on this please?

tarek : )

**Comment by tareko** [comment]
Haven't forgotten about this. I will poke @shakersh again and will address this issue myself in the coming days if he's not able.

tarek : )

**Comment by shakersh** [comment]
@sbamueller Hello and sorry for missing
there is some instruction for made your tourniquet
go to tourniquetmedia repo. you will see the file

**Comment by tareko** [comment]
Thank you so much, @shakersh ! 

@sbamueller : Here are the instructions:

https://github.com/GliaX/tourniquetmedia

**Comment by tareko** [comment]
OK, I've pulled these instructions into the main repo and converted them to markdown. I will close this issue now.
