### ISSUE TITLE
Line 70 needs language corrected

### ISSUE THREAD

**Issue by jenwilsonglia** [GliaX/tourniquet#35]
Line 70 needs language corrected from "back plate" to "bridge of back plate"

**Comment by darigovresearch** [comment]
@jenwilsonglia happy to make a pull request to change this if this is still a problem.

What was the file ?

Couldn't find `back plate` on line 70 of any file currently

https://github.com/search?q=repo%3AGliaX%2Ftourniquet+back+plate&type=code

**Comment by jenwilsonglia** [comment]
This issue has been resolved, but we forgot to close it. Thanks for bringing it to our attention.
