### ISSUE TITLE
[FEATURE REQUEST] Add source files for user instructions

### ISSUE THREAD

**Issue by darigovresearch** [GliaX/tourniquet#55]
Can see that currently user instructions are in .pdf form, having the source files would make it easier to make other language translations

https://github.com/GliaX/tourniquet/tree/master/user_instructions

**Comment by jenwilsonglia** [comment]
We'll put this on the agenda for the next tourniquet meeting on Oct. 18th

**Comment by darigovresearch** [comment]
Thanks for the update, happy to jump on a call if that helps to discuss this & other items if the timings work

**Comment by jenwilsonglia** [comment]
User instructions are very specific and having them translated by anyone isn't feasible. If anyone wants to have the user instructions translated into a specific language, please create an issue to do so.
