### ISSUE TITLE
[FEATURE REQUEST] Add release

### ISSUE THREAD

**Issue by darigovresearch** [GliaX/tourniquet#56]
Would be nice to have a V1.0.0 (or a V0.1.0) release in GitHub to make it clearer to see when there are major & minor releases.

Instructions on how to do this for reference can be seen [here](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)

**Comment by jenwilsonglia** [comment]
We'll put this on the agenda for the next tourniquet meeting on Oct. 18th

**Comment by jenwilsonglia** [comment]
This will be discussed with Tarek for final decision as to the version numbering.

**Comment by jenwilsonglia** [comment]
Current version of parts will be on the repo, but we won't be changing the version names. The most up-to-date parts should be used as the most current version. Once the parts have been updated, the previous version should no longer be used.
