### ISSUE TITLE
[FEATURE REQUEST] Source files for images with text

### ISSUE THREAD

**Issue by darigovresearch** [GliaX/tourniquet#57]
Thought it may be helpful to have the source files of images to help with making updates if the design changes but also in particular for any text in images that will require changes in the text for translations

Example of French assembly instructions but with English text in the images

Alternative is to have any text to be outside of the image so images don't need to be translated

**Comment by jenwilsonglia** [comment]
Still working on this...

**Comment by jenwilsonglia** [comment]
All raw photos for assembly instructions that had text, have now been uploaded into the assets folder with no text.

**Comment by darigovresearch** [comment]
Thanks for the updates and for the raw files. What software do you use to make the images with the text?

**Comment by jenwilsonglia** [comment]
Hi George,

I used Gimp to make the images with the text.

-Jen

March 2, 2024 10:04 AM, "Darigov Research" ***@***.*** ***@***.******@***.***>)> wrote:
	Thanks for the updates and for the raw files. What software do you use to make the images with the text?

**Comment by jenwilsonglia** [comment]
I used Gimp to make the images with text.
