### ISSUE TITLE
Translate assembly instructions to Russian

### ISSUE THREAD

**Issue by tareko** [GliaX/tourniquet#6]
David O agreed to do this.

**Comment by tareko** [comment]
We can work here, @denysgochar. As per your offer in Issue #16. Thank you!

**Comment by DenysGonchar** [comment]
Working on it, will submit translation today/tomorrow.

**Comment by defo89** [comment]
Do you need help with this translation?

**Comment by DenysGonchar** [comment]
The translation is done, but after a proof reading a couple of points are identified as unclear. Currently I'm working on additional graphic materials, to avoid any misinterpretation. Would you like to review it once it's done?

**Comment by defo89** [comment]
Sure, if Russian skills is the only pre-requisite, I am happy to review your PR.

**Comment by darigovresearch** [comment]
Is this issue okay to close as there are currently assembly instructions in Russian?

https://github.com/GliaX/tourniquet/blob/master/assembly_instructions/INSTRUCTIONS_RU.md

**Comment by DenysGonchar** [comment]
I think so.

**Comment by jenwilsonglia** [comment]
Closing due to Russian assembly instructions having been translated.
