### ISSUE TITLE
Include quality control folder on the main readme

### ISSUE THREAD

**Issue by apopanda** [GliaX/tourniquet#64]
https://github.com/GliaX/tourniquet/tree/master/assembly_instructions/quality_control folder contains very useful things, but we aren't linking to it from the main readme. We should add a heading and link to it explaining the files

**Comment by darigovresearch** [comment]
Thanks for raising the issue @apopanda, do you want to make another pull request for this?

**Comment by apopanda** [comment]
@darigovresearch sorry, no time at the moment, I'm full in device production mode right now

**Comment by jenwilsonglia** [comment]
@darigovresearch I've linked the QA folder in the Readme file.

**Comment by jenwilsonglia** [comment]
I'm going to close this out, but let me know if there is an issue with the link.

**Comment by apopanda** [comment]
Need to add it to the polish translation later
